/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica5.View;

import com.mycompany.practica5.Controller.ImageHandler;
import java.awt.event.ItemEvent;

/**
 *
 * @author pabloantoniolopezmartin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private boolean noeffect = false;
    private boolean blue=true;
    private boolean green=true;
    private boolean red=true;
            
    public MainJFrame() {
        ImageHandler.setImage();
     
        initComponents();
      
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2 = new com.mycompany.practica5.View.Lienzo();
        jPanel1 = new javax.swing.JPanel();
        redCheckBox = new javax.swing.JCheckBox();
        greenCheckBox = new javax.swing.JCheckBox();
        blueCheckBox = new javax.swing.JCheckBox();
        allCheckBox = new javax.swing.JCheckBox();
        titleLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        redCheckBox.setSelected(true);
        redCheckBox.setText("Rojo");
        redCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                redCheckBoxItemStateChanged(evt);
            }
        });
        redCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redCheckBoxActionPerformed(evt);
            }
        });

        greenCheckBox.setSelected(true);
        greenCheckBox.setText("Verde");
        greenCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                greenCheckBoxItemStateChanged(evt);
            }
        });

        blueCheckBox.setSelected(true);
        blueCheckBox.setText("Azul");
        blueCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blueCheckBoxItemStateChanged(evt);
            }
        });

        allCheckBox.setSelected(true);
        allCheckBox.setText("Todos");
        allCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                allCheckBoxItemStateChanged(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLabel.setText("RGB PICKER");

        authorsLabel.setText("Azael Santana Enríquez y Pablo López Martín");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(redCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(greenCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allCheckBox))))
                    .addComponent(authorsLabel))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redCheckBox)
                    .addComponent(greenCheckBox)
                    .addComponent(blueCheckBox)
                    .addComponent(allCheckBox))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redCheckBoxActionPerformed
       
    }//GEN-LAST:event_redCheckBoxActionPerformed

    private void redCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_redCheckBoxItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            red=true;
            ImageHandler.unApplyFilter("Red");
            lienzo2.repaint();
        }else if(evt.getStateChange() == ItemEvent.DESELECTED){
            red=false;
            noeffect= true;allCheckBox.setSelected(false);noeffect=false;
            if(!blue && !green){
               greenCheckBox.setSelected(true); 
            }
            ImageHandler.applyFilter("Red");
            lienzo2.repaint();
        }
    }//GEN-LAST:event_redCheckBoxItemStateChanged

    private void greenCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_greenCheckBoxItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            green=true;
            ImageHandler.unApplyFilter("Green");
            lienzo2.repaint();
        }else if(evt.getStateChange() == ItemEvent.DESELECTED){
            green=false;
            noeffect= true;allCheckBox.setSelected(false);noeffect=false;
            if(!green && !red){
               blueCheckBox.setSelected(true); 
            }
            ImageHandler.applyFilter("Green");
            lienzo2.repaint();
        }
    }//GEN-LAST:event_greenCheckBoxItemStateChanged

    private void blueCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blueCheckBoxItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            blue=true;
            ImageHandler.unApplyFilter("Blue");
            lienzo2.repaint();
        }else if(evt.getStateChange() == ItemEvent.DESELECTED){
            blue=false;
            noeffect= true; allCheckBox.setSelected(false);noeffect=false;
            if(!red && !green){
               redCheckBox.setSelected(true); 
            }
            ImageHandler.applyFilter("Blue");
            lienzo2.repaint();
        }
    }//GEN-LAST:event_blueCheckBoxItemStateChanged

    private void allCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_allCheckBoxItemStateChanged
        if(!noeffect){
            if(evt.getStateChange() == ItemEvent.SELECTED){
                redCheckBox.setSelected(true);
                blueCheckBox.setSelected(true);
                greenCheckBox.setSelected(true);
            }else if(evt.getStateChange() == ItemEvent.DESELECTED){
                redCheckBox.setSelected(true);
                blueCheckBox.setSelected(false);
                greenCheckBox.setSelected(false);
                lienzo2.repaint();
            }
        }
    }//GEN-LAST:event_allCheckBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allCheckBox;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JCheckBox blueCheckBox;
    private javax.swing.JCheckBox greenCheckBox;
    private javax.swing.JPanel jPanel1;
    private com.mycompany.practica5.View.Lienzo lienzo2;
    private javax.swing.JCheckBox redCheckBox;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
